### ISSUE TITLE
License file

### ISSUE THREAD

**Issue by chrismdp** [chrismdp/pairzone#7]
We need to license pairzone. MIT or BSD should do ok... Thoughts anyone?

**Comment by patchfx** [comment]
I would GPL it, I think in the case of pairzone it should stay open source, with the option for you to license it to companies if they want to use it for commercial purposes.

Just my 2 cents :)

**Comment by chrismdp** [comment]
That's a fair point, actually. By all means commit the relevant license file to master! :)

**Comment by patchfx** [comment]
Done :)

**Comment by chrismdp** [comment]
Awesome, thanks!
